### ISSUE TITLE
Fork/Clone,   Spring boot Initialization 관련

### ISSUE THREAD

**Issue by JSH0905** [Team-MansuMugang/mansumugang-backend#4]
프로젝트 초기설정을 위한 Fork 및 Clone을 진행하였습니다.
이후 git에서 git flow init 과정을 거쳤습니다.

프로젝트 build과정에서 자바 버전 관련 오류가 발생하여 임시방편으로 build.gradle파일에서 자바 버전 21로 설정하였습니다.
팀장님은 확인 후 답변 부탁드립니다.

**Comment by minnnisu** [comment]
어떠한 상황인지 확실히 알 수 없어 추후 미팅을 통해 논의하도록 하겠습니다.

**Comment by JSH0905** [comment]
회의 후 해결되어 close하겠습니다.
